# Generated by Django 3.2.9 on 2021-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='name',
        ),
        migrations.AddField(
            model_name='joke',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
