# Generated by Django 3.2.9 on 2021-11-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_auto_20211126_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Název'),
        ),
    ]
